# Generated by Django 5.1.6 on 2025-02-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='register',
            name='age',
        ),
        migrations.RemoveField(
            model_name='register',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='register',
            name='phone',
        ),
    ]
