# Generated by Django 5.1.6 on 2025-04-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_register_username_remove_register_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
