# Generated by Django 5.1.6 on 2025-04-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_symptom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
